name: Linux tests

on: [workflow_dispatch] #Manually
#on: [push]
#on:
#  workflow_run:
#    workflows: ["Build"]
#    types:
#      - completed

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14'] 
    - name: Build a wheel via an sdist
      run: |
        pip install build
        python -m build
        pip install dist/PyImageLabeling*.whl
    - name: Run test suite
      run: |
        python3 -u -m PyImageLabeling -tests